//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contigencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class destinatario_persona
    {
        public int id_destinatarios { get; set; }
        public int id_personas { get; set; }
        public int id { get; set; }
    
        public virtual destinatario destinatario { get; set; }
        public virtual persona persona { get; set; }
    }
}
