//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contigencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destinatario
    {
        public Destinatario()
        {
            this.Persona = new HashSet<Persona>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_planescontigencia { get; set; }
    
        public virtual PlanContingencia PlanContingencia { get; set; }
        public virtual ICollection<Persona> Persona { get; set; }
    }
}
