//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contigencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escenario
    {
        public Escenario()
        {
            this.Condicion = new HashSet<Condicion>();
            this.PlanContingencia = new HashSet<PlanContingencia>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<Condicion> Condicion { get; set; }
        public virtual ICollection<PlanContingencia> PlanContingencia { get; set; }
    }
}
