//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contigencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class escenario_condicion
    {
        public int id_escenarios { get; set; }
        public int id_condiciones { get; set; }
        public bool activo { get; set; }
        public int id { get; set; }
    
        public virtual condicione condicione { get; set; }
        public virtual escenario escenario { get; set; }
    }
}
