//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contigencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class escenario
    {
        public escenario()
        {
            this.condiciones = new HashSet<condicione>();
            this.planescontingencias = new HashSet<planescontingencia>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<condicione> condiciones { get; set; }
        public virtual ICollection<planescontingencia> planescontingencias { get; set; }
    }
}
