//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contigencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instruccion
    {
        public Instruccion()
        {
            this.PlanContingencia = new HashSet<PlanContingencia>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> activo { get; set; }
        public byte[] Instructivo { get; set; }
        public string InstructivoNombre { get; set; }
    
        public virtual ICollection<PlanContingencia> PlanContingencia { get; set; }
    }
}
