//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contigencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public persona()
        {
            this.destinatarios = new HashSet<destinatario>();
        }
    
        public int id { get; set; }
        public string razon_social { get; set; }
        public string email { get; set; }
        public string celular { get; set; }
        public string compañia { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual ICollection<destinatario> destinatarios { get; set; }
    }
}
