//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contigencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Destinatario = new HashSet<Destinatario>();
        }
    
        public int id { get; set; }
        public string razon_social { get; set; }
        public string email { get; set; }
        public string celular { get; set; }
        public string compañia { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual ICollection<Destinatario> Destinatario { get; set; }
    }
}
