//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contigencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_instruccion
    {
        public int id_planescontigencia { get; set; }
        public int id_instrucciones { get; set; }
        public int id { get; set; }
    
        public virtual instruccione instruccione { get; set; }
        public virtual planescontingencia planescontingencia { get; set; }
    }
}
